workflows:
  ios-workflow:
    name: PIR Hub iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: development
        bundle_identifier: com.seyitahmetkaris.pirhub
    scripts:
      - name: Paketler
        script: flutter pub get
      - name: CocoaPods
        script: |
          cd ios
          pod install
      - name: Xcode imza ayarlari
        script: xcode-project use-profiles
      - name: IPA derle
        script: |
          flutter build ipa --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

  android-workflow:
    name: PIR Hub Android APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Paketler
        script: flutter pub get
      - name: APK derle
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
